// plugins/piropo.js

// No se necesitan dependencias externas

// --- Lista de Piropos ---
// Movida desde 'global.piropo' para encapsularla en el plugin
const piropos = [
  'Me gustaría ser papel para poder envolver ese bombón.',
  'Eres como wifi sin contraseña, todo el mundo te busca.',
  'Quién fuera bus para andar por las curvas de tu corazón.',
  'Quiero volar sin alas y salir de este universo, entrar en el tuyo y amarte en silencio.',
  'Quisiera ser mantequilla para derretirme en tu arepa.',
  'Si la belleza fuera pecado vos ya estarías en el infierno.',
  'Me Gustaría Ser Un Gato Para Pasar 7 Vidas A Tu Lado.',
  'Robar Está Mal Pero Un Beso De Tu Boca Sí Me Lo Robaría.',
  'Qué Hermoso Es El Cielo Cuando Está Claro Pero Más Hermoso Es El Amor Cuando Te Tengo A Mi Lado.',
  'Bonita, Camina Por La Sombra, El Sol Derrite Los Chocolates.',
  'Si Fuera Un Correo Electrónico Serías Mi Contraseña.',
  'Quisiera que fueses monte para darte machete.',
  'Perdí mi número de teléfono ¿Me das el tuyo?',
  '¿Cómo te llamas para pedirte de regalo a Santa Claus?',
  'En el cielo hay muchas estrellas, pero la más brillante está en la Tierra y eres tú.',
  '¿Acaba de salir el sol o es la sonrisa que me regalas hoy?',
  'No es el ron ni la cerveza, eres tú quien se me ha subido a la cabeza.',
  'Si hablamos de matemáticas eres la suma de todos mis deseos.',
  'Pareces Google porque tienes todo lo que yo busco.',
  'Mi café favorito, es el de tus ojos.',
  'Quiero ser photoshop para retocarte todo el cuerpo.',
  'Quisiera que fueras cereal, para cucharearte en las mañanas.',
  'Quien fuera hambre, para darte tres veces al día.',
  'Eres la luna que ilumina mi noche oscura.',
  'Si fueras una flor, serías la más hermosa del jardín.',
  'No necesito un mapa, porque siempre me pierdo en tus ojos.',
  'Si fueras un sueño, nunca querría despertar.',
  '¿Sabías que el sol sale todos los días por ti?',
  'Tu sonrisa es mi sol en un día nublado.',
  'Si fueras una estrella, serías la más brillante en el cielo.',
  'Contigo me siento en el paraíso.',
  'Mi amor por ti es como una estrella, siempre está allí.',
  'Tus ojos tienen el poder de derretir mi corazón.',
  'Eres como el viento, me acaricias sin verlo venir.',
  'Tu risa es mi melodía favorita.',
  'Si la belleza fuera un crimen, tú estarías en la cárcel.',
  'Mi vida tiene sentido solo porque existes.',
  'Eres como un sueño hecho realidad.',
  'No hay un día que no me enamore más de ti.',
  'Cada vez que te miro, encuentro un nuevo motivo para amarte.',
  '¿Sabes qué es lo más bonito de mi día? Verte sonreír.',
  'Si pudiera ser cualquier cosa, sería tu sombra para estar cerca de ti siempre.',
  'Te amo más de lo que las palabras pueden expresar.',
  'Eres mi razón para sonreír todos los días.',
  'Tu belleza me deja sin palabras.',
  'Tu mirada tiene la magia de cautivar mi alma.',
  'Si fueras una canción, serías la melodía perfecta.',
  'Eres el sueño que jamás quiero despertar.',
  'Contigo todo es posible, porque mi corazón late solo por ti.',
  'Eres como un perfume en el aire, imposible de olvidar.',
  'Si fueras una estrella fugaz, mi deseo sería siempre estar contigo.',
  'Tus ojos son dos luceros que iluminan mi camino.',
  'Tu voz es mi melodía preferida.',
  'Eres mi sol, mi luna y todas mis estrellas.',
  'Quiero ser el viento para acariciar tu piel.',
  'Contigo cada día es un regalo.',
  'Eres el amor que nunca supe que necesitaba.',
  'Si mi corazón fuera un jardín, tú serías la flor más bonita.',
  'Tu sonrisa ilumina todo lo que toca.',
  'Eres el único pensamiento en mi mente, día y noche.',
  'Si fueras un sueño, nunca quiero despertar.',
  'Quiero ser el aire para estar cerca de ti siempre.',
  'Si fueras un poema, serías el más bonito que jamás haya existido.',
  'Eres la razón por la que creo en el amor verdadero.',
  'Tu amor me da fuerzas para seguir cada día.',
  'Eres mi razón para sonreír incluso en los días más grises.',
  'En un mundo lleno de gente, tú eres mi único pensamiento.',
  'Cada vez que te miro, el mundo parece detenerse.',
  'Eres la melodía que da ritmo a mi vida.',
  'Si fueras una estrella, siempre brillarías más que todas las demás.',
  'Eres el sueño que nunca quiero despertar.',
  'En tus ojos veo mi futuro, lleno de amor y felicidad.',
  'Si fuera un pájaro, volaría a tu lado todos los días.',
  'Mi vida no sería la misma sin ti a mi lado.',
  'Tu belleza es tan grande como el cielo mismo.',
  'Eres mi amor eterno, mi razón para seguir adelante.',
  'Te amo más de lo que las palabras pueden expresar.',
  'Si fueras un libro, serías mi capítulo favorito.',
  'Eres mi mayor deseo hecho realidad.',
  'Tu amor llena mi vida de luz y felicidad.',
  'No sé cómo lo haces, pero siempre logras hacerme sonreír.',
  'Eres el mejor regalo que la vida me ha dado.',
  'Tu amor es lo único que necesito para ser feliz.',
  'Si pudiera vivir en tu sonrisa, viviría para siempre.',
  'En tus brazos encuentro mi hogar, mi paz y mi felicidad.',
  'Eres lo que siempre busqué y nunca pensé encontrar.',
  'Si fueras una pintura, serías una obra maestra.',
  'Tu risa es mi sonido favorito en el mundo.',
  'Si fueras un poema, serías el más hermoso que jamás haya existido.',
  'Eres la razón por la que mi corazón late con fuerza cada día.',
  'Mi vida no sería la misma sin ti.',
  'Eres mi amor eterno, mi sol en un día nublado.',
  'Tu sonrisa ilumina mi vida.',
  'Te amo más que a nada en este mundo.',
  'Si pudiera darte un mundo, te daría todo el mío.',
  'Cada día contigo es un regalo del cielo.',
  'Mi corazón late más rápido solo con verte.',
  'Eres mi alegría, mi vida, mi amor eterno.',
  'Solo tú tienes la capacidad de hacerme sonreír en cualquier momento.',
  'Eres todo lo que siempre quise.',
  'Tu belleza es más que perfecta.',
  'Si fueras una flor, serías la más rara y hermosa del jardín.',
  'Mi vida no tiene sentido sin ti.',
  'Eres mi sueño hecho realidad.',
  'Si fueras una canción, te pondría en repeat todos los días.',
  'Si fueras un diamante, serías el más valioso del mundo.',
  'Tu amor es todo lo que necesito para ser feliz.',
  'Eres como una estrella, brillando con luz propia.',
  'Tu sonrisa es el reflejo de lo que es un amor verdadero.',
  'Si fueras un sueño, nunca quisiera despertar.',
  'Tus ojos tienen el poder de cautivarme a cada instante.',
  'Eres la persona que convierte un día ordinario en algo especial.',
  'Tus labios son mi lugar favorito.',
  'Contigo, hasta lo más simple se vuelve perfecto.',
  'Me haces pensar que la perfección sí existe.',
  'Si fueras un poema, serías el verso más bello.',
  'Tus ojos son dos lunas llenas que iluminan mi vida.',
  'Eres mi razón para sonreír cada día.',
  'Tu risa es la melodía que alegra mi corazón.',
  'No sé cómo haces, pero cada vez que te miro, me siento más afortunado.',
  'Si fueras una flor, serías la más hermosa del jardín.',
  'Tu belleza hace que el sol brille más.',
  'Eres mi lugar feliz.',
  'Solo una mirada tuya puede hacer que mi día sea perfecto.',
  'Tu presencia hace que todo a mi alrededor sea más bonito.',
  'Eres el sol que ilumina mis días oscuros.',
  'El mejor lugar del mundo es donde tú estés.',
  'Cada segundo a tu lado es un regalo.',
  'Tu voz es mi música favorita.',
  'Si fueras una estrella, serías la más brillante del firmamento.',
  'Eres la razón por la que mi corazón late más rápido.',
  'Si pudiera ser algo, sería un suspiro para estar cerca de ti.',
  'Tu mirada me hace sentir que todo es posible.',
  'Lo que más amo de ti es tu forma de ser.',
  'La vida es más bonita contigo en ella.',
  'El mundo es más hermoso cuando te veo sonreír.',
  'Eres mi sol en un día nublado.',
  'Eres tan perfecta que podría pasarme toda la vida mirándote.',
  'Si pudiera cambiar una cosa de ti, no cambiaría nada.',
  'Tus ojos son los más hermosos que he visto.',
  'Cada día me enamoro más de ti.',
  'Tenerte cerca es mi mayor deseo hecho realidad.',
  'Contigo, todo parece posible.',
  'Eres la melodía que me hace sentir feliz.',
  'Tenerte a mi lado es un sueño hecho realidad.',
  'Tu sonrisa es el faro que guía mi vida.',
  'Eres la persona que he estado buscando toda mi vida.',
  'Si fueras un libro, serías el capítulo que más quiero leer.',
  'La vida tiene más sentido desde que llegaste a mi vida.',
  'Tu belleza no tiene comparación.',
  'Eres la persona que hace que todo valga la pena.',
  'Me haces sentir que el amor verdadero sí existe.',
  'Eres la flor más hermosa del jardín de la vida.',
  'Siempre logras hacer que mi corazón lata más rápido.',
  'Eres mi razón para seguir adelante.',
  'Me siento afortunado solo de conocerte.',
  'Si fueras una canción, serías mi favorita.',
  'Tú eres mi inspiración cada día.',
  'Tu risa es la melodía más hermosa que escucho.',
  'No existe nada más bello que tu alma.',
  'Tu presencia ilumina mi vida como el sol ilumina el día.',
  'Cada vez que te veo, me haces sentir como si fuera el único en el mundo.',
  'Eres lo que siempre busqué y no sabía que necesitaba.',
  'Tenerte en mi vida es un regalo del destino.',
  'Eres la razón por la que sonrío todos los días.',
  'No importa lo que pase, siempre querré estar a tu lado.',
  'Mi vida cambió para mejor desde que te conocí.',
  'Eres el regalo más hermoso que la vida me ha dado.',
  'Lo mejor de mi día es verte sonreír.',
  'Me haces sentir que todo es posible.',
  'Cada momento contigo es un tesoro.',
  'Tu belleza hace que todo lo demás desaparezca.',
  'Eres la melodía perfecta en la canción de mi vida.',
  'Cuando estoy contigo, todo tiene más sentido.',
  'Tu dulzura hace que todo sea más bonito.',
  'Cada día que paso contigo es el mejor de mi vida.',
  'Tu esencia es lo que hace que mi mundo sea tan especial.',
  'Eres la estrella que ilumina mi vida.',
  'Solo tú puedes hacerme sentir tan especial.',
  'Cada vez que me miras, siento que el tiempo se detiene.',
  'Tus abrazos son mi lugar seguro.',
  'Eres la razón por la que mi corazón late más fuerte.',
  'Siempre que te veo, mi día mejora.',
  'Eres la persona que me hace ver la vida de una manera más bonita.',
  'Tus ojos son mi lugar favorito.',
  'Me haces sentir el hombre/la mujer más afortunado/a del mundo.',
  'Tu amor me da fuerzas para seguir adelante.',
  'Cuando pienso en ti, me siento en paz.',
  'Me haces ver lo mejor de cada día.',
  'Mi corazón solo late por ti.',
  'Eres la luz que ilumina mi camino.',
  'Nada me hace más feliz que estar a tu lado.',
  'Si pudiera pedir un deseo, sería que estemos juntos para siempre.',
  'Eres lo mejor que me ha pasado en la vida.',
  'Tu sonrisa ilumina incluso los días más oscuros.',
  'El amor que siento por ti no tiene palabras suficientes.',
  'Eres la razón por la que mi vida es tan colorida.',
  'Cada vez que me hablas, me haces sentir especial.',
  'Mi vida es más feliz solo por tenerte.',
  'Eres el sueño que nunca quiero despertar.',
  'Si fuera un pintor, te pintaría todos los días.',
  'Eres mi pensamiento constante y mi deseo más grande.',
  'Si pudiera pedir un deseo, sería tenerte siempre a mi lado.',
  'Tu belleza es tan infinita como el universo.',
  'Me haces sentir que soy capaz de todo.',
  'Eres el faro que ilumina mi vida.',
  'Cuando pienso en ti, mi corazón sonríe.',
  'Cada vez que sonríes, el mundo se vuelve más bonito.',
  'Tu risa es la melodía más dulce que puedo escuchar.',
  'Eres mi inspiración diaria para ser mejor persona.',
  'Me encantaría pasar toda mi vida contigo.',
  'Solo tú sabes cómo hacerme sentir tan bien.',
  'Si fueras un sueño, nunca quisiera despertar.',
  'Eres la estrella que ilumina mi vida.',
  'Tu belleza es lo que me mantiene en pie cada día.',
  'Si fueras un sol, iluminarías todo lo que te rodea.',
  'Tenerte cerca es un regalo que agradezco cada día.',
  'Eres la persona que me hace querer ser mejor.',
  'Tu forma de ser es lo que me hace enamorarme más de ti cada día.',
  'No hay nada más hermoso que tu alma.',
  'Si fueras una flor, serías la más hermosa del jardín.',
  'No necesito nada más que estar a tu lado.',
  'Tu presencia hace que todo sea más bonito.',
  'Cada vez que te veo, me haces sentir especial.',
  'Eres la razón por la que me levanto cada día con una sonrisa.',
  'Tus ojos tienen la magia de iluminar todo lo que tocan.',
  'Eres mi sol, mi luna, mi todo.',
  'Si fuera un pintor, te pintaría todos los días.',
  'Tú eres el sueño que nunca quiero despertar.',
  'Tu sonrisa es lo único que necesito para ser feliz.',
  'Eres mi mundo entero.',
  'Cuando estás cerca, todo lo demás desaparece.',
  'Tu presencia me hace sentir en paz.',
  'Eres la joya más valiosa que jamás haya existido.',
  'Me haces ver la vida de una forma más hermosa.',
  'Si fueras un poema, serías el más bonito del mundo.',
  'Tu amor es todo lo que necesito para vivir.',
  'Eres mi razón para ser feliz.',
  'Tu amor me llena de paz y felicidad.',
  'Siempre estaré agradecido/a por haberte encontrado.',
  'Eres el centro de mi universo.',
  'Me siento afortunado/a de tenerte en mi vida.',
  'Eres mi todo, mi razón de vivir.',
  'Cada vez que te miro, me enamoro más de ti.',
  'Eres la razón por la que mi corazón late más fuerte.',
  'Tu presencia hace que todo sea más brillante.',
  'Si fueras un suspiro, serías el más dulce.',
  'Tu mirada me hace sentir tan vivo/a.',
  'Eres todo lo que siempre soñé.',
  'Mi vida no sería la misma sin ti.',
  'Eres el reflejo de todo lo que quiero en la vida.',
  'Tu amor es mi mayor tesoro.',
  'Si fueras una canción, serías mi favorita.',
  'El mejor lugar del mundo es a tu lado.',
  'Eres la flor más hermosa en el jardín de mi vida.',
  'Cada momento a tu lado es un sueño hecho realidad.',
  'Eres la razón de mi felicidad.',
  'Tu sonrisa es mi sol en los días nublados.',
  'Eres el mejor regalo que la vida me ha dado.',
  'No hay nadie más especial que tú para mí.',
  'Eres la melodía que da ritmo a mi vida.',
  'Cuando te veo, todo a mi alrededor se vuelve más brillante.',
  'Eres la pieza que faltaba en mi vida.',
  'Tu voz es mi sonido favorito.',
  'Eres el amor de mi vida, mi todo.',
  'Con cada beso, me haces sentir en el paraíso.',
  'Eres el sueño hecho realidad que siempre esperé.',
  'Si fueras una estrella, serías la más brillante del cielo.',
  'Tu amor es mi paz, mi refugio, mi felicidad.',
  'Si fueras un sueño, nunca querría despertar.'
];
// --- Fin Lista de Piropos ---


module.exports = {
    name: 'piropo',
    aliases: ['piropo'], // El comando para activarlo
    description: 'Envía un piropo al azar.',
    category: 'Diversión',

    async execute(client, message, args) {
        try {
            // Verificar si la lista de piropos tiene elementos
            if (piropos && piropos.length > 0) {
                // Seleccionar uno al azar
                const randomIndex = Math.floor(Math.random() * piropos.length);
                const selectedPiropo = piropos[randomIndex];

                // Enviar el piropo seleccionado
                // Usamos un formato simple, puedes ajustarlo si quieres
                await message.reply(`😉 *Piropo:* ${selectedPiropo}`);

            } else {
                // Si por alguna razón la lista está vacía
                console.warn("[Piropo] La lista de piropos está vacía.");
                await message.reply("Parece que me quedé sin piropos por ahora.");
            }
        } catch (error) {
            console.error('[Piropo] Error al ejecutar el comando:', error);
            await message.reply("😅 ¡Uy! Algo salió mal al buscar un piropo. Intenta de nuevo.");
        }
    }
};